configfile: "./config/config.yml"
include: "rules/preprocess-reference.smk"
include: "rules/preprocess-1000-genomes.smk"
include: "rules/pedigree-sims.smk"
include: "rules/gargammel.smk"
include: "rules/preprocess-fastq.smk"


g1k_url = config["1000g"]["url"]

def my_samples(wildcards):
	with checkpoints.get_samples.get().output[0].open() as f:
		return expand("results/01-gargammel/fastqs/{sample}_s{for_rev}.fq.gz", for_rev=[1,2], sample=str.split(f.readline().replace('\n',''),'\t'))




rule ped_sim:
    input: expand("results/00-ped-sim/{POP}-pedigrees-M2-m2-snps-merged.vcf.gz", POP=config["ped-sim"]["params"]["pop"])

rule gargammel:
    input:
        my_samples

rule all:
    input:
        rules.ped_sim.input,
        rules.gargammel.input
