netrules:
  retries:          20
  1000g-phase3-url: "ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502"
  1240K-url:        "https://reichdata.hms.harvard.edu/pub/datasets/amh_repo/curated_releases/V52/V52.2/SHARE/public.dir/v52.2_1240K_public.tar"
  hapmapII:         "http://ftp.ncbi.nlm.nih.gov/hapmap/recombination/2011-01_phaseII_B37/genetic_map_HapMapII_GRCh37.tar.gz"
  reference-genomes:
    grch37:
      url : "http://ftp.ensembl.org/pub/grch37/release-113/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz"
      path: "data/reference-genome/GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa"
    hs37d5:
      url : "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz"
      path: "data/reference-genome/hs37d5/hs37d5.fa"
    human_g1k_v37:
      url : "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz"
      path: "data/reference-genome/human_g1k_v37/human_g1k_v37.fasta"
  ped-sim:
    interference-map-url:    "raw.githubusercontent.com/williamslab/ped-sim/master/interfere/nu_p_campbell.tsv"
    refined-genetic-map-url: "github.com/cbherer/Bherer_etal_SexualDimorphismRecombination/raw/master/Refined_genetic_map_b37.tar.gz"
  TKGWV2:
    support-files-url: "https://drive.google.com/drive/folders/1Aw-0v_7CUorHJOLpCJ0QVCwEdH43HlO4"
    support-files-dir: "data/TKGWV2"
  