netrules:
  retries:          20
  1000g-phase3-url: "ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502"
  hapmapII:         "http://ftp.ncbi.nlm.nih.gov/hapmap/recombination/2011-01_phaseII_B37/genetic_map_HapMapII_GRCh37.tar.gz"
  aadr-dataset:
    server-url: "https://dataverse.harvard.edu"
    persistent-id: "doi:10.7910/DVN/FFIDCW"
    dataverse-version-dict:
      v62.0   : 9.0
      v54.1.p1: 8.0
      v54.1   : 7.0
      v52.2   : 6.0
      v50.0.p1: 5.0
      v50.0   : 4.0
      v44.3   : 3.0
      #v42.4   : 2.0
      #v37.2   : 1.0
  reference-genomes:
    grch37:
      url : "http://ftp.ensembl.org/pub/grch37/release-113/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz"
      path: "data/reference-genome/GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa"
    hs37d5:
      url : "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz"
      path: "data/reference-genome/hs37d5/hs37d5.fa"
    human_g1k_v37:
      url : "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz"
      path: "data/reference-genome/human_g1k_v37/human_g1k_v37.fasta"
  ped-sim:
    interference-map-url:    "raw.githubusercontent.com/williamslab/ped-sim/master/interfere/nu_p_campbell.tsv"
    refined-genetic-map-url: "github.com/cbherer/Bherer_etal_SexualDimorphismRecombination/raw/master/Refined_genetic_map_b37.tar.gz"
    data:
      default-map:  "data/ped-sim/recombination_maps/refined_mf.simmap"
      default-interference: "data/ped-sim/interference_maps/nu_p_campbell.tsv"
  TKGWV2:
    support-files-url:          "https://drive.google.com/drive/folders/1Aw-0v_7CUorHJOLpCJ0QVCwEdH43HlO4"
    support-files-dir:          "data/TKGWV2"
    default-target-frequencies: "data/TKGWV2/1240K/1000GP3_EUR_1240K.frq"
  
