FTP:
  retries: 20
  refgen: "ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/"
  1000g : "ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502"

refgen: "data/refgen/GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa"

ped-sim:
  input: 
    interference-map-url:    "raw.githubusercontent.com/williamslab/ped-sim/master/interfere/nu_p_campbell.tsv"
    refined-genetic-map-url: "github.com/cbherer/Bherer_etal_SexualDimorphismRecombination/raw/master/Refined_genetic_map_b37.tar.gz"
  data:
    codes:          "resources/ped-sim/ped-definition/test-pedigree_codes.txt" 
    definition:     "resources/ped-sim/ped-definition/test-pedigree.def"
    map:            "data/ped-sim/recombination_maps/refined_mf.simmap"
    interference:   "data/ped-sim/interference_maps/nu_p_campbell.tsv"
  output:
    directory: "results/00-ped-sim"
  params:
    error_rate:  0
    missingness: 0
    pop: "CEU"
gargammel:
  coverage: 0.05
  comp_endo: 1.0
  comp_cont: 0
  comp_bact: 0
  misincorporation: "resources/gargammel/misincorporations/MT23-misincorporation.txt"
  sizefreq:         "resources/gargammel/sizefreqs/Ust_Ishim_sizefreq.size.gz"
  params:
    contam-pop: "AFR"
preprocess:
  trimming:
    min-overlap: 1
    min-length: 17
  bwa:
    aligner: "mem"
  filter:
    min-MQ: 30
  dedup:
    max-length: 200
kinship:
  targets: "data/vcf/1000g-phase3/02-merged/CEU.merged.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.m2.M2.maf05.vcf.gz"
  READ:
    window-size: 10
  GRUPS:
    pedigree: "workflow/scripts/grups/resources/pedigrees/simple_pedigree.txt"
    pedigree-pop: "EUR"
    contam-pop: "AFR"
    mode: "fst"
    reps: 10


