name: Ubuntu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    name: "Install"
    runs-on: "ubuntu-latest"
    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        auto-update-conda: true
        activate-environment: ""
    - name: Conda info
      run: conda info
    - name: Install Badger
      run: bash ./badger/install.sh
    - name: Run tests
      run: bash ./badger/install.sh test
